<?php

namespace AppBundle\Repository;

/**
 * AdTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
