<?php

namespace AppBundle\Repository;

/**
 * IdTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
